# Generated by Django 4.1.1 on 2022-12-16 11:04

from django.db import migrations, models
import welcomepg.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='observation',
        ),
        migrations.AddField(
            model_name='event',
            name='observation',
            field=models.JSONField(default=welcomepg.models.obser_json),
        ),
    ]
